version: '2'

services:

  rabbit:
    image: rabbitmq:3.7
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: ${RABBITMQ_HOSTNAME}
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_USE_LONGNAME=true
    ports:
      - "15672:15672"
      - "1883:1883"
      - "8883:8883"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "35197:35197"
      - "25672:25672"
#    command: echo 'NODENAME=rabbit@${RABBITMQ_HOSTNAME}' > /etc/rabbitmq/rabbitmq-env.conf

#  rabbitmq2:
#    image: cyrilix/rabbitmq-mqtt
#    hostname: rabbitmq2
#    depends_on:
#      - rabbitmq1
#    environment:
#      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
#    volumes:
#      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
#    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    
#  haproxy:
#    image: haproxy:1.7
#    volumes:
#      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
#    depends_on:
#      - rabbitmq1
#      - rabbitmq2
#      - rabbitmq3
#    ports:
#      - 15672:15672
#      - 5672:5672
